### ISSUE TITLE
Hi Greg,

### ISSUE THREAD

**Issue by mnahangi** [gschivley/Visualization-tutorial#1]

**Comment by mnahangi** [comment]
Hi Greg, 
I was trying to go through this tutorial, however, I don't think the "house" function is defined. I am getting an error for that. Would you please advise.

**Comment by gschivley** [comment]
Sure thing - "house" is a dataframe that is loaded in the Data Import 
section at the bottom of the notebook (https://nbviewer.jupyter.org/github/gschivley/Visualization-tutorial/blob/master/Visualization%20tutorial.ipynb#Data-import). Looking back I realize this is a bit
confusing.
